
version: '3.8'

services:
  # MySQL Database Service
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Som1234567
      MYSQL_DATABASE: micro_service_product_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecart-network

  # Product Service Application
  product-service:
    image: ${REGISTRY_USERNAME}/product-service:latest
    container_name: product-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Som1234567
      - EUREKA_HOST=eureka-server
    depends_on:
      - mysql-db
    volumes:
      - ./logs:/app/logs
    networks:
      - ecart-network

networks:
  ecart-network:
    driver: bridge

volumes:
  mysql_data:
