spring.application.name=product-service

# App Port Configuration
server.port=8081


# Standalone MySQL DB Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/micro_service_product_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Som1234567
spring.jpa.hibernate.ddl-auto=update

# Connect to Independent Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/



# =====================================================================
# Logging & Log Rotation Configuration
# =====================================================================
logging.file.name=logs/app-error.log
logging.level.root=INFO
logging.level.com.microservice.ecart.product-service=DEBUG


logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.max-history=7